### ISSUE TITLE
ImportError: cannot import name 'Structure' from 'pymatgen' (unknown location)

### ISSUE THREAD

**Issue by 003shwe** [henniggroup/electronic-structure-visualization#1]
I simply downloaded the repository and the dash_test.py file is missing. 
Other is i run the dash_main.py file with given test data folder included the same repository and i came across the following error. 
ImportError: cannot import name 'Structure' from 'pymatgen' (unknown location)
I am using conda pymatgen version == 2022.0.14. Kindly respond if you resolve the issue or otherwise please advise if i needed to downgrade my pymatgen package. Thanks. 
Dr. Kumari

**Comment by aztan2** [comment]
Hi,
Thanks for giving the visualization tool a try. Unfortunately, it is not something I am working on actively at the moment, hence it hadn't been updated since 2020. However, since these seem to be minor issues, I have gone ahead and fixed it and updated the scripts in the repo.

1. dash_test.py was renamed to dash_main.py
2. This error is due to the recent updates to pymatgen v2022 onwards (see the announcement on https://pymatgen.org/). The fix simply requires a small change to the import line, which I have changed in dash_main.py. It now works on my machine with pymatgen v2022.0.14.

**Comment by 003shwe** [comment]
Dear Author,
Thanks for reply. the error has been resolved after updating pymatgen.
